# -*- coding: utf-8 -*-
"""Instruction_finetuning_T5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zmqD1mb2w3lmXECIdYHhoiWaZJOhUaWr
"""

!pip install transformers datasets torch accelerate gradio -q

from transformers import (
    AutoTokenizer, AutoModelForMaskedLM, DataCollatorForLanguageModeling,
    Trainer, TrainingArguments, T5ForConditionalGeneration, T5Tokenizer, pipeline
)

from datasets import Dataset
import gradio as gr
import torch
import pandas as pd

sample_text = "Large Language Models generate human-like text."

# Tokenizer and model (DistilBERT for simplicity)
tokenizer_demo = AutoTokenizer.from_pretrained("distilbert-base-uncased")
model_demo = AutoModelForMaskedLM.from_pretrained("distilbert-base-uncased")

tokens = tokenizer_demo.tokenize(sample_text)
print(" Tokens:", tokens)

input_ids = tokenizer_demo(sample_text, return_tensors="pt").input_ids
embeddings = model_demo.distilbert.embeddings.word_embeddings(input_ids)
print("Embedding shape:", embeddings.shape)

data = pd.read_csv('/content/train.csv')

# Ensure all object columns are treated as strings to avoid conversion errors
for col in data.select_dtypes(include='object').columns:
    data[col] = data[col].astype(str)

dataset = Dataset.from_list(data.to_dict('records'))

# Tokenization / preprocessing
model_name = "t5-small"
tokenizer = T5Tokenizer.from_pretrained(model_name, use_auth_token=False)

def preprocess(example):
    inp = f"Instruction: {example['instruction']} Input: {example['input']}"
    model_inputs = tokenizer(inp, truncation=True, padding="max_length", max_length=128)
    labels = tokenizer(example["output"], truncation=True, padding="max_length", max_length=128)
    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

tokenized_data = dataset.map(preprocess, batched=False)

model = T5ForConditionalGeneration.from_pretrained(model_name, use_auth_token=False)

training_args = TrainingArguments(
    output_dir="./t5_instruction_finetune",
    learning_rate=3e-5,
    per_device_train_batch_size=2,
    num_train_epochs=2,
    weight_decay=0.01,
    logging_dir="./logs",
    save_strategy="no",
    push_to_hub=False,        # <— prevents token prompt
    report_to=[]              # <— disables any reporting
)

trainer = Trainer(model=model, args=training_args, train_dataset=tokenized_data)
trainer.train()
trainer.save_model("./t5_instruction_model")

pipe = pipeline("text2text-generation", model="./t5_instruction_model", tokenizer=model_name)

def generate_text(instruction, user_input):
    prompt = f"Instruction: {instruction} Input: {user_input}"
    result = pipe(prompt, max_length=80)[0]['generated_text']
    return result

demo = gr.Interface(
    fn=generate_text,
    inputs=[gr.Textbox(label="Instruction (e.g. Summarize the text)"),
            gr.Textbox(label="Input Text")],
    outputs=gr.Textbox(label="Generated Output"),
    title=" Mini GenAI Instruction Model (Token-Free)",
    description="Fine-tuned T5-small model trained"
)

demo.launch()

import shutil
from google.colab import files

# Define the directory to zip
dir_to_zip = "/content/t5_instruction_model"
output_filename = "t5_instruction_model"

# Create a zip archive
shutil.make_archive(output_filename, 'zip', dir_to_zip)

# Provide the zip file for download
files.download(f"{output_filename}.zip")